import { TopStocks } from "../types/types";

export const top_stocks: TopStocks = {
  "AAPL": "Apple Inc.",
  "ABT": "Abbott Laboratories",
  "ACN": "Accenture plc",
  "ADBE": "Adobe Inc.",
  "ADI": "Analog Devices Inc.",
  "ADM": "Archer-Daniels-Midland Company",
  "ADP": "Automatic Data Processing Inc.",
  "ADSK": "Autodesk Inc.",
  "AEE": "Ameren Corporation",
  "AEP": "American Electric Power Company Inc.",
  "AES": "The AES Corporation",
  "AFL": "Aflac Inc.",
  "AIG": "American International Group Inc.",
  "AIZ": "Assurant Inc.",
  "AJG": "Arthur J. Gallagher & Co.",
  "AKAM": "Akamai Technologies Inc.",
  "ALB": "Albemarle Corporation",
  "ALGN": "Align Technology Inc.",
  "ALK": "Alaska Air Group Inc.",
  "ALL": "The Allstate Corporation",
  "ALLE": "Allegion plc",
  "ALXN": "Alexion Pharmaceuticals Inc.",
  "AMAT": "Applied Materials Inc.",
  "AMD": "Advanced Micro Devices Inc.",
  "AME": "AMETEK Inc.",
  "AMGN": "Amgen Inc.",
  "AMP": "Ameriprise Financial Inc.",
  "AMT": "American Tower Corporation",
  "AMZN": "Amazon.com Inc.",
  "ANET": "Arista Networks Inc.",
  "ANSS": "ANSYS Inc.",
  "AON": "Aon plc",
  "APA": "Apache Corporation",
  "APD": "Air Products and Chemicals Inc.",
  "APH": "Amphenol Corporation",
  "APTV": "Aptiv PLC",
  "ARE": "Alexandria Real Estate Equities Inc.",
  "ATO": "Atmos Energy Corporation",
  "ATR": "AptarGroup Inc.",
  "ATVI": "Activision Blizzard Inc.",
  "AVB": "AvalonBay Communities Inc.",
  "AVGO": "Broadcom Inc.",
  "AVY": "Avery Dennison Corporation",
  "AWK": "American Water Works Company Inc.",
  "AXP": "American Express Company",
  "AYI": "Acuity Brands Inc.",
  "BA": "The Boeing Company",
  "BAC": "Bank of America Corporation",
  "BAX": "Baxter International Inc.",
  "BBY": "Best Buy Co. Inc.",
  "BDX": "Becton Dickinson and Company",
  "BE": "Bloom Energy Corporation",
  "BEN": "Franklin Templeton Investments",
  "BF.B": "Brown-Forman Corporation",
  "BG": "Bunge Limited",
  "BHF": "Brighthouse Financial Inc.",
  "BIIB": "Biogen Inc.",
  "BMY": "Bristol-Myers Squibb Company",
  "BOH": "Bank of Hawaii Corporation",
  "BXP": "Boston Properties Inc.",
  "C": "Citigroup Inc.",
  "CAG": "ConAgra Brands Inc.",
  "CAH": "Cardinal Health Inc.",
  "CAT": "Caterpillar Inc.",
  "CB": "Chubb Limited",
  "CBOE": "Cboe Global Markets Inc.",
  "CBRE": "CBRE Group Inc.",
  "CCL": "Carnival Corporation",
  "CDW": "CDW Corporation",
  "CE": "Celanese Corporation",
  "CERN": "Cerner Corporation",
  "CF": "CF Industries Holdings Inc.",
  "CFG": "Citizens Financial Group Inc.",
  "CHTR": "Charter Communications Inc.",
  "CI": "Cigna Corporation",
  "CINF": "Cincinnati Financial Corporation",
  "CL": "Colgate-Palmolive Company",
  "CLX": "Clorox Co.",
  "CMA": "Comerica Inc.",
  "CMCSA": "Comcast Corporation",
  "CME": "CME Group Inc.",
  "CMG": "Chipotle Mexican Grill Inc.",
  "CMI": "Cummins Inc.",
  "CMS": "CMS Energy Corporation",
  "CNC": "Centene Corporation",
  "CNP": "CenterPoint Energy Inc.",
  "COF": "Capital One Financial Corporation",
  "COG": "Cabot Oil & Gas Corporation",
  "COL": "Rockwell Collins Inc.",
  "COST": "Costco Wholesale Corporation",
  "COTY": "Coty Inc.",
  "CRL": "Charles River Laboratories International Inc.",
  "CRM": "Salesforce.com Inc.",
  "CSCO": "Cisco Systems Inc.",
  "CSX": "CSX Corporation",
  "CTAS": "Cintas Corporation",
  "CTSH": "Cognizant Technology Solutions Corporation",
  "CTVA": "Corteva Inc.",
  "CVS": "CVS Health Corporation",
  "D": "Dominion Energy Inc.",
  "DAL": "Delta Air Lines Inc.",
  "DD": "DuPont de Nemours Inc.",
  "DE": "Deere & Company",
  "DHR": "Danaher Corporation",
  "DIS": "Walt Disney Company",
  "DLO": "DLocal S.A.",
  "DOV": "Dover Corporation",
  "DTE": "DTE Energy Company",
  "DUO": "Duo Security",
  "DVA": "DaVita Inc.",
  "DXC": "DXC Technology Company",
  "EA": "Electronic Arts Inc.",
  "EBAY": "eBay Inc.",
  "ECL": "Ecolab Inc.",
  "ED": "Consolidated Edison Inc.",
  "EFX": "Equifax Inc.",
  "EIX": "Edison International",
  "EL": "Estée Lauder Companies Inc.",
  "EMR": "Emerson Electric Co.",
  "ENB": "Enbridge Inc.",
  "ENDP": "Endo International plc",
  "ET": "Energy Transfer LP",
  "ETN": "Eaton Corporation plc",
  "ETSY": "Etsy Inc.",
  "EVRG": "Evergy Inc.",
  "EXC": "Exelon Corporation",
  "EXPD": "Expeditors International of Washington Inc.",
  "F": "Ford Motor Company",
  "FAST": "Fastenal Company",
  "FB": "Meta Platforms Inc.",
  "FIS": "Fidelity National Information Services Inc.",
  "FISV": "FISV",
  "FITB": "Fifth Third Bank",
  "FLIR": "FLIR Systems Inc.",
  "FMC": "FMC Corporation",
  "FND": "Floor & Decor Holdings Inc.",
  "FOX": "Fox Corporation",
  "FOXA": "Fox Corporation",
  "FRC": "First Republic Bank",
  "FRT": "Federal Realty Investment Trust",
  "FTNT": "Fortinet Inc.",
  "FTV": "Fortive Corporation",
  "GD": "General Dynamics Corporation",
  "GE": "General Electric Company",
  "GILD": "Gilead Sciences Inc.",
  "GIS": "General Mills Inc.",
  "GLW": "Corning Inc.",
  "GM": "General Motors Company",
  "GNRC": "Generac Holdings Inc.",
  "GOOGL": "Alphabet Inc.",
  "GPC": "Genuine Parts Company",
  "GPN": "Global Payments Inc.",
  "GRMN": "Garmin Ltd.",
  "GS": "Goldman Sachs Group Inc.",
  "GWW": "W.W. Grainger Inc.",
  "HAL": "Halliburton Company",
  "HAS": "Hasbro Inc.",
  "HCA": "HCA Healthcare Inc.",
  "HD": "Home Depot Inc.",
  "HES": "Hess Corporation",
  "HIG": "Hartford Financial Services Group Inc.",
  "HII": "Huntington Ingalls Industries Inc.",
  "HPE": "Hewlett Packard Enterprise Company",
  "HPQ": "HP Inc.",
  "HRB": "H&R Block Inc.",
  "HRL": "Hormel Foods Corporation",
  "HSBC": "HSBC Holdings plc",
  "HUM": "Humana Inc.",
  "IBM": "IBM Corporation",
  "ICE": "Intercontinental Exchange Inc.",
  "IDXX": "IDEXX Laboratories Inc.",
  "IEX": "IDEX Corporation",
  "IHD": "iShares iBoxx $ High Yield Corporate Bond ETF",
  "IFF": "International Flavors & Fragrances Inc.",
  "ILMN": "Illumina Inc.",
  "INCY": "Incyte Corporation",
  "INTC": "Intel Corporation",
  "INTU": "Intuit Inc.",
  "INVH": "Invitation Homes Inc.",
  "IP": "International Paper Company",
  "IQV": "IQVIA Holdings Inc.",
  "IR": "Ingersoll Rand Inc.",
  "IRM": "Iron Mountain Inc.",
  "ISRG": "Intuitive Surgical Inc.",
  "J": "Jacobs Engineering Group Inc.",
  "JBHT": "J.B. Hunt Transport Services Inc.",
  "JCI": "Johnson Controls International plc",
  "JPM": "JPMorgan Chase & Co.",
  "K": "Kellogg Company",
  "KHC": "Kraft Heinz Company",
  "KLAC": "KLA Corporation",
  "KMB": "Kimberly-Clark Corporation",
  "KMI": "Kinder Morgan Inc.",
  "KMX": "CarMax Inc.",
  "KO": "Coca-Cola Company",
  "KORS": "Michael Kors Holdings Ltd.",
  "KR": "Kroger Co.",
  "KSS": "Kohl's Corporation",
  "KSU": "Kansas City Southern",
  "L": "Loews Corporation",
  "LDOS": "Leidos Holdings Inc.",
  "LEG": "Leggett & Platt Incorporated",
  "LEN": "Lennar Corporation",
  "LH": "Laboratory Corporation of America Holdings",
  "LMT": "Lockheed Martin Corporation",
  "LNC": "Lincoln National Corporation",
  "LIN": "Linde plc",
  "LKQ": "LKQ Corporation",
  "LLY": "Eli Lilly and Company",
  "LMT": "Lockheed Martin Corporation",
  "LNC": "Lincoln National Corporation",
  "LNT": "Alliant Energy Corporation",
  "LOW": "Lowe's Companies Inc.",
  "LUV": "Southwest Airlines Co.",
  "MAC": "The Macerich Company",
  "MAR": "Marriott International Inc.",
  "MAS": "Masco Corporation",
  "MA": "Mastercard Incorporated",
  "MAT": "Mattel Inc.",
  "MCD": "McDonald's Corporation",
  "MCK": "McKesson Corporation",
  "MDLZ": "Mondelez International Inc.",
  "MDT": "Medtronic plc",
  "MET": "MetLife Inc.",
  "MGM": "MGM Resorts International",
  "MHK": "Mohawk Industries Inc.",
  "MLM": "Martin Marietta Materials Inc.",
  "MMC": "Marsh & McLennan Companies Inc.",
  "MMM": "3M Company",
  "MO": "Altria Group Inc.",
  "MON": "Monsanto Company",
  "MRO": "Marathon Oil Corporation",
  "MS": "Morgan Stanley",
  "MSCI": "MSCI Inc.",
  "MSFT": "Microsoft Corporation",
  "MTB": "M&T Bank Corporation",
  "MTD": "MTD Products Inc.",
  "MU": "Micron Technology Inc.",
  "MUR": "Murphy Oil Corporation",
  "NCLH": "Norwegian Cruise Line Holdings Ltd.",
  "NDAQ": "Nasdaq Inc.",
  "NEE": "NextEra Energy Inc.",
  "NEM": "Newmont Corporation",
  "NFLX": "Netflix Inc.",
  "NI": "NiSource Inc.",
  "NKE": "Nike Inc.",
  "NLOK": "NortonLifeLock Inc.",
  "NOC": "Northrop Grumman Corporation",
  "NOV": "National Oilwell Varco Inc.",
  "NRG": "NRG Energy Inc.",
  "NSC": "Norfolk Southern Corporation",
  "NUE": "Nucor Corporation",
  "NVDA": "Nvidia Corporation",
  "NVR": "NVR Inc.",
  "O": "Realty Income Corporation",
  "ODFL": "Old Dominion Freight Line Inc.",
  "OHI": "Omega Healthcare Investors Inc.",
  "OI": "O-I Glass Inc.",
  "OKE": "OneMain Holdings Inc.",
  "OMC": "Omnicom Group Inc.",
  "ON": "ON Semiconductor Corporation",
  "ORCL": "Oracle Corporation",
  "OXY": "Occidental Petroleum Corporation",
  "PAYC": "Paycor HCM Inc.",
  "PAYX": "Paychex Inc.",
  "PCG": "PG&E Corporation",
  "PFE": "Pfizer Inc.",
  "PG": "Procter & Gamble Co.",
  "PGR": "Progressive Corporation",
  "PH": "Parker-Hannifin Corporation",
  "PKI": "PerkinElmer Inc.",
  "PLD": "Prologis Inc.",
  "PLTR": "Palantir Technologies Inc.",
  "PM": "Philip Morris International Inc.",
  "PNC": "PNC Financial Services Group Inc.",
  "PPL": "PPL Corporation",
  "PRU": "Prudential Financial Inc.",
  "PSA": "Public Storage",
  "PSX": "Phillips 66",
  "PVH": "PVH Corp.",
  "QCOM": "Qualcomm Incorporated",
  "QRVO": "Qorvo Inc.",
  "RCL": "Royal Caribbean Group",
  "RE": "Evercore Inc.",
  "REG": "Regency Centers Corporation",
  "REGN": "Regeneron Pharmaceuticals Inc.",
  "RF": "Regions Financial Corporation",
  "RHI": "Robert Half International Inc.",
  "RJF": "Raymond James Financial Inc.",
  "RL": "Ralph Lauren Corporation",
  "ROK": "Rockwell Automation Inc.",
  "ROL": "Rollins Inc.",
  "ROST": "Ross Stores Inc.",
  "RRC": "Range Resources Corporation",
  "RSG": "Republic Services Inc.",
  "RTX": "Raytheon Technologies Corporation",
  "SBUX": "Starbucks Corporation",
  "SCHW": "Charles Schwab Corporation",
  "SE": "Sea Limited",
  "SHW": "Sherwin-Williams Company",
  "SIVB": "SVB Financial Group",
  "SLB": "Schlumberger Limited",
  "SNA": "Snap-On Inc.",
  "SNPS": "Synopsys Inc.",
  "SO": "Southern Company",
  "SPG": "Simon Property Group Inc.",
  "SPY": "SPDR S&P 500 ETF Trust",
  "SQ": "Square Inc.",
  "SSP": "E.W. Scripps Company",
  "STT": "State Street Corporation",
  "STZ": "Constellation Brands Inc.",
  "SWKS": "Skyworks Solutions Inc.",
  "SYK": "Stryker Corporation",
  "SYY": "Sysco Corporation",
  "T": "AT&T Inc.",
  "TAP": "Molson Coors Beverage Company",
  "TDG": "TransDigm Group Incorporated",
  "TEL": "TE Connectivity Ltd.",
  "TFC": "Truist Financial Corporation",
  "TMO": "Thermo Fisher Scientific Inc.",
  "TMUS": "T-Mobile US Inc.",
  "TROW": "T. Rowe Price Group Inc.",
  "TRV": "The Travelers Companies Inc.",
  "TSCO": "Tractor Supply Company",
  "TSLA": "Tesla Inc.",
  "TSN": "Tyson Foods Inc.",
  "TWTR": "Twitter Inc.",
  "TXN": "Texas Instruments Incorporated",
  "UNH": "UnitedHealth Group Incorporated",
  "UPS": "United Parcel Service Inc.",
  "URI": "United Rentals Inc.",
  "USB": "U.S. Bancorp",
  "UTX": "United Technologies Corporation",
  "V": "Visa Inc.",
  "VAR": "Varian Medical Systems Inc.",
  "VFC": "V.F. Corporation",
  "VLO": "Valero Energy Corporation",
  "VRTX": "Vertex Pharmaceuticals Incorporated",
  "WBA": "Walgreens Boots Alliance Inc.",
  "WDC": "Western Digital Corporation",
  "WEC": "WEC Energy Group Inc.",
  "WELL": "Welltower Inc.",
  "WFC": "Wells Fargo & Company",
  "WHD": "Cactus Inc.",
  "WHR": "Whirlpool Corporation",
  "WMT": "Walmart Inc.",
  "WRB": "W. R. Berkley Corporation",
  "WST": "West Pharmaceutical Services Inc.",
  "WTW": "Willis Towers Watson Public Limited Company",
  "XOM": "Exxon Mobil Corporation",
  "XRX": "Xerox Holdings Corporation",
  "XYL": "Xylem Inc.",
  "YUM": "Yum! Brands Inc.",
  "ZBH": "Zimmer Biomet Holdings Inc.",
  "ZBRA": "Zebra Technologies Corporation",
  "ZION": "Zions Bancorporation",
  "ZTS": "Zoetis Inc."
};


export const options = Object.entries(top_stocks).map(([symbol, name]) => ({
  label: `${symbol} - ${name}`,
  value: symbol,
}));