name: Client CI

on:
  push:
    branches: [main]
    paths:
      - 'client/**'
      - '.github/workflows/client-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'client/**'
      - '.github/workflows/client-ci.yml'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci
      #   Add linter later
      # - name: Lint
      #   run: npm run lint

      - name: Test frontend
        run: npm run test -- --no-color --run
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: ./client/coverage/
          retention-days: 7

  deploy-client:
    needs: test-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy Client
        run: echo "Add your client deployment steps here"