name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]  # Added to run tests on PRs as well

jobs:
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4  # Updated to latest version
        with:
          fetch-depth: 0  # Only fetch what's necessary

      - name: Set up Python 3.10
        uses: actions/setup-python@v5  # Updated to latest version
        with:
          python-version: '3.10'
          cache: 'pip'  # Added pip caching

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest
        env:
          PYTHONPATH: ${{ github.workspace }}/server  # Added PYTHONPATH

      - name: Upload test results
        if: always()  # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: ./server/pytest-results/
          retention-days: 7

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint  # Added linting step if you have it configured

      - name: Test frontend
        run: npm run test -- --no-color --run
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-results
          path: ./client/coverage/
          retention-days: 7

  deploy:
    needs: [test-server, test-frontend]  # Added deployment job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy
        run: echo "Add your deployment steps here"
        # Add your actual deployment steps