name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  # Backend Testing Job
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 500
          fetch-tags: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest  


  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - name: Run npm CI
        run: npm ci
      - name: Test frontend
        run: npm run test -- --no-color --run

